version: 2
jobs:
  build:
    docker:
      - image: base/archlinux
    steps:
      - checkout
      - run: pacman -Syu --noconfirm
      - run: pacman -S --noconfirm archiso
      - run:
          command: ./build.sh
          working_directory: ~/project/64/xfce
